name: Build & Publish Resume

on:
  push:
    branches:
      - master

concurrency: build-and-publish-on-master

jobs:
  publish:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write      
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - name: Install deps
        run: bun install
      - name: Build Resume
        run: bun run export      
      - name: Deploy
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ascrazy-me
          directory: public/
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main